### ISSUE TITLE
There is a bug in the team section

### ISSUE THREAD

**Issue by sammy429b** [MLSCMMCOE/mlsc-website#19]
If you click on any member of another cohort (eg. cloud) member social handle link and come back to again mlsc website it will render core member detail.
![Screenshot 2023-10-15 185716](https://github.com/MLSCMMCOE/mlsc-website/assets/97588853/c0b2adfa-2f00-4417-9a84-ea31a384f7ab)
Images of some members are missing.

**Comment by asyncdoggo** [comment]
Not necessarily a bug imo, but I would suggest we open external links in new tab.

**Comment by asyncdoggo** [comment]
Current the selected domain is handled in CSS, I have added social links to open in new tab to temporarily fix it. 
Will keep this issue open until proper fix.
