### ISSUE TITLE
⚠️ Redirection from `Contact Us` page is broken 

### ISSUE THREAD

**Issue by Atharv-Nalwade** [MLSCMMCOE/mlsc-website#36]
## Bug Description :
I've encountered a bug in the current implementation of our routing system. When you visit the 'Contact Us' page and then attempt to access other tabs, such as "About," "Team," or others, the expected behavior is not being achieved. This issue stems from a discrepancy in the URL within the navbar.

## Details:
The issue becomes evident when you access the 'Contact Us' page. The URL in the navbar doesn't update as expected when you navigate to other tabs. This results in unintended behavior, as the routing system fails to recognize the change in the selected tab.

## Reproduction Steps:

- Visit the 'Contact Us' page.
- Observe the URL in the navbar.
- Attempt to navigate to other tabs, such as "About" or "Team."

## Expected Behavior:
The URL in the navbar should dynamically update when switching between different tabs within the page, ensuring that the navigation system functions as intended.

Happy Hacking 🚀

**Comment by Atharv-Nalwade** [comment]
Dear Maintainers,
If no one takes this up In a week I would like to be assigned to this one. 😅

**Comment by asyncdoggo** [comment]
Did fix it this morning, forgot to deploy :p
