### ISSUE TITLE
Add tabs for events section

### ISSUE THREAD

**Issue by asyncdoggo** [MLSCMMCOE/mlsc-website#6]
Add tabs with upcoming and past events in events section on home page, we can have the blog cards and blogs and for upcoming events we can have registration cards.

**Comment by Thilagavathi1** [comment]
Hi @asyncdoggo 
is there any design available to work on this

**Comment by Raman01010010** [comment]
please assign i want  to work on it.

**Comment by Raman01010010** [comment]
> Add tabs with upcoming and past events in events section on home page, we can have the blog cards and blogs and for upcoming events we can have registration cards.

please elaborate so i can start now

**Comment by asyncdoggo** [comment]
> > Add tabs with upcoming and past events in events section on home page, we can have the blog cards and blogs and for upcoming events we can have registration cards.
> 
> please elaborate so i can start now

Basically we need tabs for section named Upcoming events and past events similar to how team section has, Upcoming events will have cards with some image and a short description and a redirection button for registration form, past events will be a short summary for a blog with link to the blog with event image as card image and title of the card and certain short description, upon opening redirect to a blog link, 
We do not have a design but following something similar to team cards would work.
Let me know if any more help is necessary.
