### ISSUE TITLE
The 'visit gallery' button background is slightly greyish.

### ISSUE THREAD

**Issue by disha3006** [MLSCMMCOE/mlsc-website#7]
The visit gallery button background is greyish compared to the entire website background , we could try changing the background to #fbfbfb00 hex . Also the cursor pointer property is given to the entire div that the button is in, instead of just the button.

**Comment by Thilagavathi1** [comment]
Hi @asyncdoggo @disha3006 i would like to work on this issue.could u assign this issue to me?

**Comment by asyncdoggo** [comment]
> Hi @asyncdoggo @disha3006 i would like to work on this issue.could u assign this issue to me?

Sure

**Comment by Thilagavathi1** [comment]
@asyncdoggo @disha3006 Raised an [PR](https://github.com/MLSCMMCOE/mlsc-website/pull/10) for this issue.Please check it
