### ISSUE TITLE
Add team members information

### ISSUE THREAD

**Issue by asyncdoggo** [MLSCMMCOE/mlsc-website#9]
Add all team member's data to team_data.jsx

**Comment by DarkSoul26** [comment]
@asyncdoggo can I take a look into this?

**Comment by asyncdoggo** [comment]
Sure, use [12bc95d](https://github.com/MLSCMMCOE/mlsc-website/commit/12bc95d7185bc493ab7f8dd39896d5af8247d6f9) for reference

**Comment by asyncdoggo** [comment]
> @asyncdoggo can I take a look into this?

Sure, use [12bc95d](https://github.com/MLSCMMCOE/mlsc-website/commit/12bc95d7185bc493ab7f8dd39896d5af8247d6f9) for reference.

**Comment by shlok-2003** [comment]
Hey @asyncdoggo, I am interested in this issue, can you please assign it to me

**Comment by asyncdoggo** [comment]
> Hey @asyncdoggo, I am interested in this issue, can you please assign it to me

I believe @DarkSoul26 is probably already looking to it.

**Comment by DarkSoul26** [comment]
Hey @asyncdoggo, from where can I get info of all the members?

**Comment by asyncdoggo** [comment]
@DarkSoul26 check directory of [This commit](https://github.com/MLSCMMCOE/mlsc-website/commit/12bc95d7185bc493ab7f8dd39896d5af8247d6f9), you will find it in the index.html

**Comment by DarkSoul26** [comment]
Hey @asyncdoggo check out #18
